version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - modernize
    - usestdlibvars
    - intrange
    - exptostd
    - prealloc
    - perfsprint
    - makezero
    - unconvert
    - wastedassign
    - gocritic
    - errorlint
    - bodyclose
    - nolintlint
  exclusions:
    rules:
      - path: testsupport/*
        linters:
          - staticcheck
      - path: _test\.go
        linters:
          - staticcheck
formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 90
      tab-len: 4
