services:
  shiftbell:
    build: .
    image: ${DEV_IMAGE}
    ports:
      - "8080:80"
    environment:
      DATABASE_FILEPATH: "/data/app.db"
    volumes:
      - "./:/src"
      - "go_build_cache:/root/.cache/go-build"
      - "go_module_cache:/go/pkg/mod"
      - "appdata:/data"
    entrypoint: ["go"]
    command: ["tool", "air"]

volumes:
  go_build_cache:
  go_module_cache:
  appdata:
