FROM golang:1.26.0-alpine AS build

WORKDIR /src

COPY go.sum go.mod ./
COPY cmd cmd
COPY internal internal

RUN go tool templ generate
RUN CGO_ENABLED=0 go build -o /app ./cmd/serve

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /app /app
ENTRYPOINT ["/app"]
