// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chores_test

import (
	"context"

	"github.com/bpsoos/shiftbell/internal/models/chores"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Browse provides a mock function for the type MockService
func (_mock *MockService) Browse(context1 context.Context, browseChoresParams *chores.BrowseChoresParams) (*chores.ChorePage, error) {
	ret := _mock.Called(context1, browseChoresParams)

	if len(ret) == 0 {
		panic("no return value specified for Browse")
	}

	var r0 *chores.ChorePage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chores.BrowseChoresParams) (*chores.ChorePage, error)); ok {
		return returnFunc(context1, browseChoresParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chores.BrowseChoresParams) *chores.ChorePage); ok {
		r0 = returnFunc(context1, browseChoresParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chores.ChorePage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *chores.BrowseChoresParams) error); ok {
		r1 = returnFunc(context1, browseChoresParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Browse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Browse'
type MockService_Browse_Call struct {
	*mock.Call
}

// Browse is a helper method to define mock.On call
//   - context1 context.Context
//   - browseChoresParams *chores.BrowseChoresParams
func (_e *MockService_Expecter) Browse(context1 any, browseChoresParams any) *MockService_Browse_Call {
	return &MockService_Browse_Call{Call: _e.mock.On("Browse", context1, browseChoresParams)}
}

func (_c *MockService_Browse_Call) Run(run func(context1 context.Context, browseChoresParams *chores.BrowseChoresParams)) *MockService_Browse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chores.BrowseChoresParams
		if args[1] != nil {
			arg1 = args[1].(*chores.BrowseChoresParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Browse_Call) Return(v *chores.ChorePage, err error) *MockService_Browse_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_Browse_Call) RunAndReturn(run func(context1 context.Context, browseChoresParams *chores.BrowseChoresParams) (*chores.ChorePage, error)) *MockService_Browse_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(context1 context.Context, createChoreParams *chores.CreateChoreParams) (*chores.CreateChoreResult, error) {
	ret := _mock.Called(context1, createChoreParams)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *chores.CreateChoreResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chores.CreateChoreParams) (*chores.CreateChoreResult, error)); ok {
		return returnFunc(context1, createChoreParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chores.CreateChoreParams) *chores.CreateChoreResult); ok {
		r0 = returnFunc(context1, createChoreParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chores.CreateChoreResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *chores.CreateChoreParams) error); ok {
		r1 = returnFunc(context1, createChoreParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - createChoreParams *chores.CreateChoreParams
func (_e *MockService_Expecter) Create(context1 any, createChoreParams any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", context1, createChoreParams)}
}

func (_c *MockService_Create_Call) Run(run func(context1 context.Context, createChoreParams *chores.CreateChoreParams)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chores.CreateChoreParams
		if args[1] != nil {
			arg1 = args[1].(*chores.CreateChoreParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(createChoreResult *chores.CreateChoreResult, err error) *MockService_Create_Call {
	_c.Call.Return(createChoreResult, err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context1 context.Context, createChoreParams *chores.CreateChoreParams) (*chores.CreateChoreResult, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(context1 context.Context, n int) (*chores.ChoreDetails, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *chores.ChoreDetails
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*chores.ChoreDetails, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *chores.ChoreDetails); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chores.ChoreDetails)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - n int
func (_e *MockService_Expecter) Get(context1 any, n any) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", context1, n)}
}

func (_c *MockService_Get_Call) Run(run func(context1 context.Context, n int)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(v *chores.ChoreDetails, err error) *MockService_Get_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(context1 context.Context, n int) (*chores.ChoreDetails, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}
