name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4
        with:
          just-version: "1.51.0"
      - run: just mockery
      - run: just test-ci
